---
title: "COVID-19 Data"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    navbar:
      - {icon: "fa-github", href: "https://github.com/alturkaa/socio-cov", align: right }
---

```{r packages, include=FALSE}
library(tidyverse)
library(tidycensus)
library(mapview)
library(tmap)
library(sf)
library(leaflet)
library(crosstalk)
library(tmaptools)
tmap_mode('view')
```

```{r get census data with shapefiles}
# B27010_051 65 and over pop
# B27010_001 total pop

vars <- c('B27010_001', 'B27010_051')

us_county_test <- get_acs(geography = "county", year = 2018, variables = vars, 
                            shift_geo = TRUE, geometry = TRUE)

counties <- us_county_test %>% 
  select(-moe) %>% 
  group_by(GEOID) %>% 
  spread(variable, estimate)

counties <- counties %>% 
  mutate(prop_65_above_acs_2018 = B27010_051 / B27010_001) %>%
  rename('Geo_FIPS' = 'GEOID',
         'Geo_QNAME' = 'NAME')
```

```{r import County Health Rankings data and merge}

health_rank_full <- read_csv('../health_county_full_2016.csv')

cols_to_keep <- c('Geo_QNAME', 'Geo_NAME', 'Geo_FIPS', 'ORG_HD2016_001_HEALTH_T6_V25', 'ORG_HD2016_001_HEALTH_T6_V13', 'ORG_HD2016_003_HEALTH_T9_V9', 'ORG_HD2016_006_HEALTH_T3_V42', 'ORG_HD2016_006_HEALTH_T3_V35', 'ORG_HD2016_006_HEALTH_T3_V25')

health_condense <- health_rank_full %>% 
  select(., all_of(cols_to_keep)) %>% 
  rename('Total Population' = 'ORG_HD2016_001_HEALTH_T6_V25',
         'Percent Population 65 and Above' = 'ORG_HD2016_001_HEALTH_T6_V13',
         'Percent Uninsured (Ages 18-64)' = 'ORG_HD2016_003_HEALTH_T9_V9',
         'Percent Without Insurance (Under 65)' = 'ORG_HD2016_006_HEALTH_T3_V42',
         'Primary Care Physicians per 100K' = 'ORG_HD2016_006_HEALTH_T3_V35',
         'Preventable Hospital Stays per 100K Medicare enrollees' = 'ORG_HD2016_006_HEALTH_T3_V25')

health_counties <- merge(counties, health_condense, by = 'Geo_FIPS')
```
```{r import cases data and merge, message=FALSE, warning=FALSE}

yesterday <- format(Sys.Date()-1, "%m-%d-%Y")

cases_url <- paste0('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/', yesterday, '.csv')

cumulative_cases_yesterday <- read_csv(cases_url)

us_cases <- cumulative_cases_yesterday %>% 
  filter(Country_Region == 'US') %>% 
  rename('Geo_FIPS' = 'FIPS',
         'Confirmed Cases' = 'Confirmed')

# length(unique(us_cases$Geo_FIPS))

cases_health_counties <- merge(health_counties, us_cases, by = 'Geo_FIPS')

cases_health_counties <- cases_health_counties %>% 
  mutate('Confirmed Cases per 10K' = `Confirmed Cases` / (B27010_001 / 10000)) %>% 
  mutate('Confirmed Cases per 100K' = `Confirmed Cases` / (B27010_001 / 100000))
```

```{r reproject and use with crosswalk}

cases_counties_final <- set_projection(cases_health_counties, projection = 'longlat')

# st_crs(shape_reproj)

# st_transform(crs = "+init=epsg:4326")

shared_cty <- SharedData$new(cases_counties_final)

# st_crs(shared_cty)

# cty_map <- tm_shape(cases_counties_final) +
#   tm_polygons('Confirmed Cases per 10K', style = 'jenks', popup.vars = c('Geo_NAME', 'Total Population', 'Percent Population 65 and Above', 'Primary Care Physicians per 100K', 'Percent Without Insurance (Under 65)', 'Confirmed Cases', 'Confirmed Cases per 10K')) +
#   tm_layout(title = "Per Capita COVID-19 Confirmed Cases By County",
#     title.size = 1,
#     title.position = c("center", "top"))

# classInt::classIntervals(cases_counties_final$`Confirmed Cases per 10K`, n = 5, style = 'jenks')

# cty_map <- st_transform(cty_map, crs = 4326)

labels <- paste0(shared_cty$data()$Geo_NAME, "<br/>", "Confirmed Cases per 10K: ", round(shared_cty$data()$`Confirmed Cases per 10K`, 1))

labels_v2 <- sprintf(
  "<strong>%s</strong><br/>Confirmed Cases per 10K: %g",
  shared_cty$data()$Geo_NAME, round(shared_cty$data()$`Confirmed Cases per 10K`, 1)
)

bins <- c(0, 1.25, 5, 20, 60, 135)

pal <- colorBin(
  palette = "YlGnBu",
  domain = cases_counties_final$`Confirmed Cases per 10K`,
  bins = bins
)

shared_leaf_map <- shared_cty %>% 
  leaflet() %>% 
  setView(-96, 37.8, 5) %>% 
  addProviderTiles(provider = "CartoDB.Positron") %>%
  addPolygons(label = lapply(labels_v2, htmltools::HTML),
    fillColor = ~pal(cases_counties_final$`Confirmed Cases per 10K`),
    stroke = TRUE,
    fillOpacity = 0.7,
    weight = 0.4) %>% 
    addLegend("bottomright",
    pal = pal,
    values = ~ `Confirmed Cases per 10K`,
    title = "Confirmed Cases per 10K",
    opacity = 1)

# cty_leaflet <- tmap_leaflet(cty_map)
```

Per Capita Cases By County
=============================================================

<!-- Sidebar1 {.sidebar} -->
<!-- ----------------------------------------------------------------------- -->

<!-- ```{r} -->
<!-- # filter_slider("prop_65_above", "Percent Population 65 and Above", shared_cty, ~prop_65_above, round = 1) -->
<!-- ``` -->

<!-- Column -->
<!-- ----------------------------------------------------------------------- -->

###

```{r map, message=FALSE, warning=FALSE}

shared_leaf_map

# cty_leaflet

# tmap_save(cty_map, filename = 'county_map_test_v2.html')

# cty_layers <- tm_shape(shape_reproj) +
#   tm_polygons(c('Confirmed Cases per 100K', 'Primary Care Physicians per 100K'),
#               style = 'jenks', 
#               popup.vars = c('Geo_NAME', 'Total Population', 'Percent Population 65 and Above', 'Primary Care Physicians per 100K', 'Percent Without Insurance (Under 65)', 'Confirmed Cases', 'Confirmed Cases per 100K'),
#               title = c('Confirmed Cases per 100K', 'Primary Care Physicians per 100K')) +
#   tm_facets(as.layers = TRUE)
#   # tm_layout(title = "Per Capita COVID-19 Confirmed Cases By County",
#   #   title.size = 1,
#   #   title.position = c("center", "top"))
# 
# cty_layers
```
> Data Sources: [Johns Hopkins University Center for Systems Science and Engineering](https://github.com/CSSEGISandData/COVID-19), [American Community Survey 2018 (5-Year Estimates)](https://www.census.gov/)